version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    # .env 파일에 정의된 환경 변수를 사용합니다.
    env_file:
      - .env

  db:
    image: mariadb:10.5
    restart: always
    environment:
      # 루트 비밀번호는 더 강력한 값으로 변경하는 것을 권장합니다.
      MYSQL_ROOT_PASSWORD: 'root_password_!@#'
      MYSQL_DATABASE: 'board'
      MYSQL_USER: 'funny'
      MYSQL_PASSWORD: 'strim100'
    ports:
      - "4807:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: